version: '3'

services:
  user_ms:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: production
      POSTGRES_URI: postgresql://postgres_user:postgres_pass@host.docker.internal:10002/vscr-cdn-user-ms
      PORT: 3000
    ports:
      - 20002:3000
    depends_on:
      - user_ms_postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - cdn_cdn

  user_ms_postgres:
    image: postgres:13.14-alpine
    restart: always
    ports:
      - 10002:5432
    volumes:
      - user_ms_postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=vscr-cdn-user-ms
    networks:
      - cdn_cdn

volumes:
  user_ms_postgres_volume:

networks:
  cdn_cdn:
    external: true
